alias ..='cd ..'
alias ...='cd ../..'
alias cls='clear'
alias p='cd ~/projects'
alias dt='cd ~/Desktop'
alias dl='cd ~/Downloads'
alias gc='git clone'
alias gs='git status'
alias gdi='git diff'
alias gco='git checkout '
alias gpo='git push origin '
alias gpo:current='git push origin "$(git rev-parse --abbrev-ref HEAD)"'
alias gcm='git commit -m '
alias ll='ls -lah'
alias vi="nvim"
alias vim="nvim"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
